config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get "users/new"

  root 'static_pages#home'
  match '/registro', to:'users#new', via: 'get'
  match '/ingreso', to:'sessions#new', via: 'get'  
  match '/salida', to:'sessions#destroy', via: 'delete'
  match '/ayuda', to:'static_pages#help', via: 'get'
  match '/acerca_de', to:'static_pages#acerca_de', via: 'get'
  match '/contacto', to:'static_pages#contacto', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save {self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length:{maximum:50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, length: {minimum: 6}
	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end
	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end
	private 
		def create_remember_token
			self.remember_token = User.digest(User.new_remember_token)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			#ingresa al usuario y lo redirecciona a la pagina del mismo
			ingreso user
			redirect_to user
		else
			flash.now[:error] = 'Combination email/password ivalida'
			render 'new'
		end
	end
	
	def destroy
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def acerca_de
  end

  def contacto
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "Bienvenido a la Sample App!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def new
  	@user = User.new
  end  
    require "prawn"
      #def pdf
        Prawn::Document.generate("Informe.pdf") do
        text "Informe de Revision", :align => :center, :size => 18
        stroke_axis( :width => 200, :height => 200, :step_length => 20, :color => 'FF00')
        stroke { line [0, 200], [100, 150] }
        fill { rectangle [0, 100], 100, 100 }
        image "#{Prawn::DATADIR}/images/prawn.png"
      #end
    end
  private 
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title= "Sample App"
		if page_title.empty?
			base_title
		else
			"#{base_title} / #{page_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def ingreso(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user
	end

	def ingresado?
		!current_user.nil?
	end
	def current_user=(user)
		@current_user = user
	end
	def current_user
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||=User.find_by(remember_token: remember_token)
	end
	def pdf
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url =  "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end		
end

app/views/layouts/_footer.html.erb
<footer class='footer'>
	<small>
		<a href='http://www.ute.edu.ec'> Universidad Tecnologica Equinoccial</a>  Quito - Ecuador
	</small>
	<nav>
		<ul>
			<li><%= link_to "Acerca de",acerca_de_path%></li>
			<li><%= link_to "Contacto",contacto_path%></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
		<div class="navbar-inner">
			<div class="container">
				<%= link_to "sample_app",root_path,id: "logo"%>
				<nav>
					<ul class="nav pull-right">
						<li><%= link_to "Inicio",root_path %></li>
						<li><%= link_to "Ayuda",ayuda_path %></li>
						<% if ingresado? %>
							<li id= "fat-menu" class= "dropdown">
								<a href="#" class= "dropdown-toggle" data-toggle="dropdown">
									Cuenta <b class="caret"></b>
								</a>
								<ul class= "dropdown-menu"></li>
									<li><%= link_to "Perfil",current_user %></li>
									<li><%= link_to "Preferencias",'#' %></li>
									<li class="divider"></li>
									<li><%= link_to "Salir",salida_path, method: "delete" %></li>
								</ul>
							</li>
						<% else %>
							<li><%= link_to "Ingresa",ingreso_path %></li>
						<% end %>
					</ul>
				</nav>
			</div>
		</div>
	</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
 <%= render 'layouts/shim'%>
</head>
<body>
	<%= render 'layouts/header'%>
	<div class="container">
		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div> 
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer'%>
		<%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
<div id = 'error_explanation'>
	<div class="alert alert-error">
		the form contains <%= pluralize(@user.errors.count, "error")  %>
	</div>
	<ul>
		<% @user.errors.full_messages.each do |msg| %>
		<li>* <%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/static_pages/acerca_de.html.erb
<% provide(:title,'Acerca de')%>
		<h1>Acerca de</h1>
		<p>
			La aplicacion Sample App ha sido desarrollada para el curso de Ruby on Rails de la <a href='http://www.ute.edu.ec'> Universidad Tecnologica Equinoccial</a>
			2014
		</p>

app/views/static_pages/contacto.html.erb
<% provide(:title,'Contacto')%>
<h1>Contacto</h1>
		<p>
			<a href='http://www.ute.edu.ec'> Universidad Tecnologica Equinoccial</a>
			2014
		</p>

app/views/static_pages/help.html.erb
<% provide(:title,'Ayuda')%>

		<h1>Ayuda</h1>
		<p>
			Pagina de ayuda para la aplicacion Sample App
		</p>
	

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Bienvenido a la aplicacion de prueba
	</h1>
	<h2>Esta es la Pagina de inicio de la aplicacion Sample App desarrollada para el curso de RoR de la <a href='http://www.ute.edu.ec'> Universidad Tecnologica Equinoccial</a>
	</h2>
	<%= link_to "registrate!",registro_path,class:"btn btn-large btn-primary"%>
</div>
<div class='logo.jpeg'>
	<%= link_to image_tag("logo.jpeg",alt:"Universidad Tecnologica Equinoccial"),'http://www.ute.edu.ec' %>
</div'>

app/views/user/new.html.erb
<% provide(:title, 'Registro')%>
<h1>Registro</h1>
<p>pagina ed registro</p>

app/views/users/new.html.erb
<% provide(:title, 'Registro')%>
<h1>Registro</h1>
<div class="row">
	<div class = "span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'shared/error_messages' %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :email %>
			<%= f.text_field :email %>

			<%= f.label :password %>
			<%= f.password_field :password %>

			<%= f.label :password_confirmation, "Confirmation" %>
			<%= f.password_field :password_confirmation %>

			<%= f.submit "Crear mi cuenta", class: "btn btn-large btn-primary"%>

		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<div class="row">
	<aside class = "span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
	</aside>
</div>
<div>
	<%= pdf %>
</div>